//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Actions/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""e0f2d3af-3d91-4585-b185-48e8473eba03"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""16025712-fe8e-45a2-bb9c-cb7ed335f9a3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ThrowCog"",
                    ""type"": ""Button"",
                    ""id"": ""f8063e8d-50fa-436c-b343-106929d8e191"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractNPC"",
                    ""type"": ""Button"",
                    ""id"": ""0689fdaf-91fa-4546-ae62-fee8d9f2e14c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseGame"",
                    ""type"": ""Button"",
                    ""id"": ""dd86e952-7694-43fc-ad1e-560dd9af6cb4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ResumeGame"",
                    ""type"": ""Button"",
                    ""id"": ""53165fe7-fd42-4a46-ac64-2c6b1f11503b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SaveGame"",
                    ""type"": ""Button"",
                    ""id"": ""1942109f-613a-4125-a967-5bb68277f022"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HomeTap"",
                    ""type"": ""Button"",
                    ""id"": ""f32e42fa-07ba-4061-ad06-e71c42362a26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SaveGameJson"",
                    ""type"": ""Button"",
                    ""id"": ""ead95c13-53cf-4e67-a6f8-52adc693b4ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""952bf805-cb1b-4e6c-863b-b26c375cc3b2"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowCog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f488ccac-4025-4770-a264-7ba5a1a46821"",
                    ""path"": ""<Touchscreen>/touch0/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowCog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""479599a0-e3ee-4b18-ae38-13dbdbdcead2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b894ae19-d655-4d2b-8f66-2ddd26f27fef"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""56a658c0-ac19-458f-86d2-c1d16a2f649f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cff48c75-988b-4fb8-85f0-37f34dd3d16d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""35fed736-76fb-47e7-85a4-bfb229265b3a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""92bc1f29-e0d5-4308-a9dd-8e65f8b23dcc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6f149961-1d49-4122-8850-7911b1d9b779"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7dfdb5d6-29d3-441d-88b5-3e503b6e1b2d"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""144820f1-725f-4e24-a22f-0cb49492c538"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""04297152-7db0-4b52-ab1a-f1a83480f484"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""268ac222-89fd-4f6e-9fa8-4177b0cb291e"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df173941-1332-451a-a78b-e97eb029498a"",
                    ""path"": ""<AndroidJoystick>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bc5bb60-6654-4d20-817d-6289ff7894e8"",
                    ""path"": ""<Touchscreen>/touch1/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractNPC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f52335d0-e36a-40fe-8b84-cf8bb0007a0f"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractNPC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e639e4e6-5b58-4cfc-b693-84412bc7c512"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29c48d1d-2361-4fd8-a101-c22290db7712"",
                    ""path"": ""<Touchscreen>/touch2/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""987ecff8-9e54-486c-b9fc-9e58a23a7014"",
                    ""path"": ""<Touchscreen>/touch3/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResumeGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3dbc1ed7-c905-41c3-938d-17be2093dfac"",
                    ""path"": ""<Touchscreen>/touch4/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SaveGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d91c7747-16a5-4f32-a4bc-fd459735c23e"",
                    ""path"": ""<Touchscreen>/touch5/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HomeTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edde4faa-0c94-4033-9b6f-c0314b6e48d3"",
                    ""path"": ""<Touchscreen>/touch6/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SaveGameJson"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_ThrowCog = m_Player.FindAction("ThrowCog", throwIfNotFound: true);
        m_Player_InteractNPC = m_Player.FindAction("InteractNPC", throwIfNotFound: true);
        m_Player_PauseGame = m_Player.FindAction("PauseGame", throwIfNotFound: true);
        m_Player_ResumeGame = m_Player.FindAction("ResumeGame", throwIfNotFound: true);
        m_Player_SaveGame = m_Player.FindAction("SaveGame", throwIfNotFound: true);
        m_Player_HomeTap = m_Player.FindAction("HomeTap", throwIfNotFound: true);
        m_Player_SaveGameJson = m_Player.FindAction("SaveGameJson", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_ThrowCog;
    private readonly InputAction m_Player_InteractNPC;
    private readonly InputAction m_Player_PauseGame;
    private readonly InputAction m_Player_ResumeGame;
    private readonly InputAction m_Player_SaveGame;
    private readonly InputAction m_Player_HomeTap;
    private readonly InputAction m_Player_SaveGameJson;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @ThrowCog => m_Wrapper.m_Player_ThrowCog;
        public InputAction @InteractNPC => m_Wrapper.m_Player_InteractNPC;
        public InputAction @PauseGame => m_Wrapper.m_Player_PauseGame;
        public InputAction @ResumeGame => m_Wrapper.m_Player_ResumeGame;
        public InputAction @SaveGame => m_Wrapper.m_Player_SaveGame;
        public InputAction @HomeTap => m_Wrapper.m_Player_HomeTap;
        public InputAction @SaveGameJson => m_Wrapper.m_Player_SaveGameJson;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @ThrowCog.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnThrowCog;
                @ThrowCog.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnThrowCog;
                @ThrowCog.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnThrowCog;
                @InteractNPC.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteractNPC;
                @InteractNPC.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteractNPC;
                @InteractNPC.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteractNPC;
                @PauseGame.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPauseGame;
                @PauseGame.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPauseGame;
                @PauseGame.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPauseGame;
                @ResumeGame.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnResumeGame;
                @ResumeGame.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnResumeGame;
                @ResumeGame.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnResumeGame;
                @SaveGame.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSaveGame;
                @SaveGame.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSaveGame;
                @SaveGame.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSaveGame;
                @HomeTap.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHomeTap;
                @HomeTap.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHomeTap;
                @HomeTap.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHomeTap;
                @SaveGameJson.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSaveGameJson;
                @SaveGameJson.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSaveGameJson;
                @SaveGameJson.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSaveGameJson;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @ThrowCog.started += instance.OnThrowCog;
                @ThrowCog.performed += instance.OnThrowCog;
                @ThrowCog.canceled += instance.OnThrowCog;
                @InteractNPC.started += instance.OnInteractNPC;
                @InteractNPC.performed += instance.OnInteractNPC;
                @InteractNPC.canceled += instance.OnInteractNPC;
                @PauseGame.started += instance.OnPauseGame;
                @PauseGame.performed += instance.OnPauseGame;
                @PauseGame.canceled += instance.OnPauseGame;
                @ResumeGame.started += instance.OnResumeGame;
                @ResumeGame.performed += instance.OnResumeGame;
                @ResumeGame.canceled += instance.OnResumeGame;
                @SaveGame.started += instance.OnSaveGame;
                @SaveGame.performed += instance.OnSaveGame;
                @SaveGame.canceled += instance.OnSaveGame;
                @HomeTap.started += instance.OnHomeTap;
                @HomeTap.performed += instance.OnHomeTap;
                @HomeTap.canceled += instance.OnHomeTap;
                @SaveGameJson.started += instance.OnSaveGameJson;
                @SaveGameJson.performed += instance.OnSaveGameJson;
                @SaveGameJson.canceled += instance.OnSaveGameJson;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnThrowCog(InputAction.CallbackContext context);
        void OnInteractNPC(InputAction.CallbackContext context);
        void OnPauseGame(InputAction.CallbackContext context);
        void OnResumeGame(InputAction.CallbackContext context);
        void OnSaveGame(InputAction.CallbackContext context);
        void OnHomeTap(InputAction.CallbackContext context);
        void OnSaveGameJson(InputAction.CallbackContext context);
    }
}
